require: rubocop-rails
AllCops:
  Exclude:
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'config.ru'
    - 'bin/**/*'
    - 'app/mailers/application_mailer.rb'
    - 'app/jobs/application_job.rb'
Style/Documentation:
  Enabled: false