require: rubocop-rails
AllCops:
  Exclude:
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'config.ru'
    - 'bin/**/*'
    - 'app/mailers/application_mailer.rb'
    - 'app/jobs/application_job.rb'
    - 'app/graphql/learn_and_remember_schema.rb'
    - 'app/controllers/graphql_controller.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 25
  Exclude:
   - 'spec/graphql/mutations/**/*'
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/graphql/mutations/**/*'
Metrics/AbcSize:
  Max: 20
